//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustExample.RemoteWcf {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteWcf.IRemoteDataService")]
    public interface IRemoteDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteDataService/GetAllAirAccount", ReplyAction="http://tempuri.org/IRemoteDataService/GetAllAirAccountResponse")]
        System.Data.DataSet GetAllAirAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteDataService/GetAllAirAccount", ReplyAction="http://tempuri.org/IRemoteDataService/GetAllAirAccountResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllAirAccountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteDataService/UploadAbroadStudent", ReplyAction="http://tempuri.org/IRemoteDataService/UploadAbroadStudentResponse")]
        string UploadAbroadStudent(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRemoteDataService/UploadAbroadStudent", ReplyAction="http://tempuri.org/IRemoteDataService/UploadAbroadStudentResponse")]
        System.Threading.Tasks.Task<string> UploadAbroadStudentAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRemoteDataServiceChannel : JustExample.RemoteWcf.IRemoteDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteDataServiceClient : System.ServiceModel.ClientBase<JustExample.RemoteWcf.IRemoteDataService>, JustExample.RemoteWcf.IRemoteDataService {
        
        public RemoteDataServiceClient() {
        }
        
        public RemoteDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllAirAccount() {
            return base.Channel.GetAllAirAccount();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllAirAccountAsync() {
            return base.Channel.GetAllAirAccountAsync();
        }
        
        public string UploadAbroadStudent(string xml) {
            return base.Channel.UploadAbroadStudent(xml);
        }
        
        public System.Threading.Tasks.Task<string> UploadAbroadStudentAsync(string xml) {
            return base.Channel.UploadAbroadStudentAsync(xml);
        }
    }
}
