//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustExample.CallFSOP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CallFSOP.FSOPServerSoap")]
    public interface FSOPServerSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 PfilePath 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generateLegFlyFSOPXML", ReplyAction="*")]
        JustExample.CallFSOP.generateLegFlyFSOPXMLResponse generateLegFlyFSOPXML(JustExample.CallFSOP.generateLegFlyFSOPXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generateLegFlyFSOPXML", ReplyAction="*")]
        System.Threading.Tasks.Task<JustExample.CallFSOP.generateLegFlyFSOPXMLResponse> generateLegFlyFSOPXMLAsync(JustExample.CallFSOP.generateLegFlyFSOPXMLRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 PfileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/submitFSOPImage", ReplyAction="*")]
        JustExample.CallFSOP.submitFSOPImageResponse submitFSOPImage(JustExample.CallFSOP.submitFSOPImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/submitFSOPImage", ReplyAction="*")]
        System.Threading.Tasks.Task<JustExample.CallFSOP.submitFSOPImageResponse> submitFSOPImageAsync(JustExample.CallFSOP.submitFSOPImageRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strAppType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppStatus", ReplyAction="*")]
        JustExample.CallFSOP.GetAppStatusResponse GetAppStatus(JustExample.CallFSOP.GetAppStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<JustExample.CallFSOP.GetAppStatusResponse> GetAppStatusAsync(JustExample.CallFSOP.GetAppStatusRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 PfileName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/submitLegFlyFSOPXML", ReplyAction="*")]
        JustExample.CallFSOP.submitLegFlyFSOPXMLResponse submitLegFlyFSOPXML(JustExample.CallFSOP.submitLegFlyFSOPXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/submitLegFlyFSOPXML", ReplyAction="*")]
        System.Threading.Tasks.Task<JustExample.CallFSOP.submitLegFlyFSOPXMLResponse> submitLegFlyFSOPXMLAsync(JustExample.CallFSOP.submitLegFlyFSOPXMLRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fileStream 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileWithCallWcf", ReplyAction="*")]
        JustExample.CallFSOP.UploadFileWithCallWcfResponse UploadFileWithCallWcf(JustExample.CallFSOP.UploadFileWithCallWcfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFileWithCallWcf", ReplyAction="*")]
        System.Threading.Tasks.Task<JustExample.CallFSOP.UploadFileWithCallWcfResponse> UploadFileWithCallWcfAsync(JustExample.CallFSOP.UploadFileWithCallWcfRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateLegFlyFSOPXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateLegFlyFSOPXML", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.generateLegFlyFSOPXMLRequestBody Body;
        
        public generateLegFlyFSOPXMLRequest() {
        }
        
        public generateLegFlyFSOPXMLRequest(JustExample.CallFSOP.generateLegFlyFSOPXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class generateLegFlyFSOPXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PfilePath;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public System.Xml.Linq.XElement xmldoc;
        
        public generateLegFlyFSOPXMLRequestBody() {
        }
        
        public generateLegFlyFSOPXMLRequestBody(string PfilePath, string fileName, System.Xml.Linq.XElement xmldoc) {
            this.PfilePath = PfilePath;
            this.fileName = fileName;
            this.xmldoc = xmldoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generateLegFlyFSOPXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generateLegFlyFSOPXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.generateLegFlyFSOPXMLResponseBody Body;
        
        public generateLegFlyFSOPXMLResponse() {
        }
        
        public generateLegFlyFSOPXMLResponse(JustExample.CallFSOP.generateLegFlyFSOPXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class generateLegFlyFSOPXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string generateLegFlyFSOPXMLResult;
        
        public generateLegFlyFSOPXMLResponseBody() {
        }
        
        public generateLegFlyFSOPXMLResponseBody(string generateLegFlyFSOPXMLResult) {
            this.generateLegFlyFSOPXMLResult = generateLegFlyFSOPXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitFSOPImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitFSOPImage", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.submitFSOPImageRequestBody Body;
        
        public submitFSOPImageRequest() {
        }
        
        public submitFSOPImageRequest(JustExample.CallFSOP.submitFSOPImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class submitFSOPImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PfileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string myfile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Token;
        
        public submitFSOPImageRequestBody() {
        }
        
        public submitFSOPImageRequestBody(string PfileName, string myfile, string Token) {
            this.PfileName = PfileName;
            this.myfile = myfile;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitFSOPImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitFSOPImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.submitFSOPImageResponseBody Body;
        
        public submitFSOPImageResponse() {
        }
        
        public submitFSOPImageResponse(JustExample.CallFSOP.submitFSOPImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class submitFSOPImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string submitFSOPImageResult;
        
        public submitFSOPImageResponseBody() {
        }
        
        public submitFSOPImageResponseBody(string submitFSOPImageResult) {
            this.submitFSOPImageResult = submitFSOPImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppStatus", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.GetAppStatusRequestBody Body;
        
        public GetAppStatusRequest() {
        }
        
        public GetAppStatusRequest(JustExample.CallFSOP.GetAppStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAppStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strAppType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strAppID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strLicenseNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Token;
        
        public GetAppStatusRequestBody() {
        }
        
        public GetAppStatusRequestBody(string strAppType, string strAppID, string strLicenseNo, string Token) {
            this.strAppType = strAppType;
            this.strAppID = strAppID;
            this.strLicenseNo = strLicenseNo;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.GetAppStatusResponseBody Body;
        
        public GetAppStatusResponse() {
        }
        
        public GetAppStatusResponse(JustExample.CallFSOP.GetAppStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAppStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAppStatusResult;
        
        public GetAppStatusResponseBody() {
        }
        
        public GetAppStatusResponseBody(string GetAppStatusResult) {
            this.GetAppStatusResult = GetAppStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitLegFlyFSOPXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitLegFlyFSOPXML", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.submitLegFlyFSOPXMLRequestBody Body;
        
        public submitLegFlyFSOPXMLRequest() {
        }
        
        public submitLegFlyFSOPXMLRequest(JustExample.CallFSOP.submitLegFlyFSOPXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class submitLegFlyFSOPXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PfileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string myfile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Token;
        
        public submitLegFlyFSOPXMLRequestBody() {
        }
        
        public submitLegFlyFSOPXMLRequestBody(string PfileName, string myfile, string Token) {
            this.PfileName = PfileName;
            this.myfile = myfile;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitLegFlyFSOPXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitLegFlyFSOPXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.submitLegFlyFSOPXMLResponseBody Body;
        
        public submitLegFlyFSOPXMLResponse() {
        }
        
        public submitLegFlyFSOPXMLResponse(JustExample.CallFSOP.submitLegFlyFSOPXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class submitLegFlyFSOPXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string submitLegFlyFSOPXMLResult;
        
        public submitLegFlyFSOPXMLResponseBody() {
        }
        
        public submitLegFlyFSOPXMLResponseBody(string submitLegFlyFSOPXMLResult) {
            this.submitLegFlyFSOPXMLResult = submitLegFlyFSOPXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileWithCallWcfRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileWithCallWcf", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.UploadFileWithCallWcfRequestBody Body;
        
        public UploadFileWithCallWcfRequest() {
        }
        
        public UploadFileWithCallWcfRequest(JustExample.CallFSOP.UploadFileWithCallWcfRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileWithCallWcfRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] fileStream;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string callFunName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string wcfCreateFileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tocken;
        
        public UploadFileWithCallWcfRequestBody() {
        }
        
        public UploadFileWithCallWcfRequestBody(byte[] fileStream, string callFunName, string fileName, string wcfCreateFileName, string tocken) {
            this.fileStream = fileStream;
            this.callFunName = callFunName;
            this.fileName = fileName;
            this.wcfCreateFileName = wcfCreateFileName;
            this.tocken = tocken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileWithCallWcfResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileWithCallWcfResponse", Namespace="http://tempuri.org/", Order=0)]
        public JustExample.CallFSOP.UploadFileWithCallWcfResponseBody Body;
        
        public UploadFileWithCallWcfResponse() {
        }
        
        public UploadFileWithCallWcfResponse(JustExample.CallFSOP.UploadFileWithCallWcfResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UploadFileWithCallWcfResponseBody {
        
        public UploadFileWithCallWcfResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FSOPServerSoapChannel : JustExample.CallFSOP.FSOPServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FSOPServerSoapClient : System.ServiceModel.ClientBase<JustExample.CallFSOP.FSOPServerSoap>, JustExample.CallFSOP.FSOPServerSoap {
        
        public FSOPServerSoapClient() {
        }
        
        public FSOPServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FSOPServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FSOPServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FSOPServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JustExample.CallFSOP.generateLegFlyFSOPXMLResponse JustExample.CallFSOP.FSOPServerSoap.generateLegFlyFSOPXML(JustExample.CallFSOP.generateLegFlyFSOPXMLRequest request) {
            return base.Channel.generateLegFlyFSOPXML(request);
        }
        
        public string generateLegFlyFSOPXML(string PfilePath, string fileName, System.Xml.Linq.XElement xmldoc) {
            JustExample.CallFSOP.generateLegFlyFSOPXMLRequest inValue = new JustExample.CallFSOP.generateLegFlyFSOPXMLRequest();
            inValue.Body = new JustExample.CallFSOP.generateLegFlyFSOPXMLRequestBody();
            inValue.Body.PfilePath = PfilePath;
            inValue.Body.fileName = fileName;
            inValue.Body.xmldoc = xmldoc;
            JustExample.CallFSOP.generateLegFlyFSOPXMLResponse retVal = ((JustExample.CallFSOP.FSOPServerSoap)(this)).generateLegFlyFSOPXML(inValue);
            return retVal.Body.generateLegFlyFSOPXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JustExample.CallFSOP.generateLegFlyFSOPXMLResponse> JustExample.CallFSOP.FSOPServerSoap.generateLegFlyFSOPXMLAsync(JustExample.CallFSOP.generateLegFlyFSOPXMLRequest request) {
            return base.Channel.generateLegFlyFSOPXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<JustExample.CallFSOP.generateLegFlyFSOPXMLResponse> generateLegFlyFSOPXMLAsync(string PfilePath, string fileName, System.Xml.Linq.XElement xmldoc) {
            JustExample.CallFSOP.generateLegFlyFSOPXMLRequest inValue = new JustExample.CallFSOP.generateLegFlyFSOPXMLRequest();
            inValue.Body = new JustExample.CallFSOP.generateLegFlyFSOPXMLRequestBody();
            inValue.Body.PfilePath = PfilePath;
            inValue.Body.fileName = fileName;
            inValue.Body.xmldoc = xmldoc;
            return ((JustExample.CallFSOP.FSOPServerSoap)(this)).generateLegFlyFSOPXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JustExample.CallFSOP.submitFSOPImageResponse JustExample.CallFSOP.FSOPServerSoap.submitFSOPImage(JustExample.CallFSOP.submitFSOPImageRequest request) {
            return base.Channel.submitFSOPImage(request);
        }
        
        public string submitFSOPImage(string PfileName, string myfile, string Token) {
            JustExample.CallFSOP.submitFSOPImageRequest inValue = new JustExample.CallFSOP.submitFSOPImageRequest();
            inValue.Body = new JustExample.CallFSOP.submitFSOPImageRequestBody();
            inValue.Body.PfileName = PfileName;
            inValue.Body.myfile = myfile;
            inValue.Body.Token = Token;
            JustExample.CallFSOP.submitFSOPImageResponse retVal = ((JustExample.CallFSOP.FSOPServerSoap)(this)).submitFSOPImage(inValue);
            return retVal.Body.submitFSOPImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JustExample.CallFSOP.submitFSOPImageResponse> JustExample.CallFSOP.FSOPServerSoap.submitFSOPImageAsync(JustExample.CallFSOP.submitFSOPImageRequest request) {
            return base.Channel.submitFSOPImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<JustExample.CallFSOP.submitFSOPImageResponse> submitFSOPImageAsync(string PfileName, string myfile, string Token) {
            JustExample.CallFSOP.submitFSOPImageRequest inValue = new JustExample.CallFSOP.submitFSOPImageRequest();
            inValue.Body = new JustExample.CallFSOP.submitFSOPImageRequestBody();
            inValue.Body.PfileName = PfileName;
            inValue.Body.myfile = myfile;
            inValue.Body.Token = Token;
            return ((JustExample.CallFSOP.FSOPServerSoap)(this)).submitFSOPImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JustExample.CallFSOP.GetAppStatusResponse JustExample.CallFSOP.FSOPServerSoap.GetAppStatus(JustExample.CallFSOP.GetAppStatusRequest request) {
            return base.Channel.GetAppStatus(request);
        }
        
        public string GetAppStatus(string strAppType, string strAppID, string strLicenseNo, string Token) {
            JustExample.CallFSOP.GetAppStatusRequest inValue = new JustExample.CallFSOP.GetAppStatusRequest();
            inValue.Body = new JustExample.CallFSOP.GetAppStatusRequestBody();
            inValue.Body.strAppType = strAppType;
            inValue.Body.strAppID = strAppID;
            inValue.Body.strLicenseNo = strLicenseNo;
            inValue.Body.Token = Token;
            JustExample.CallFSOP.GetAppStatusResponse retVal = ((JustExample.CallFSOP.FSOPServerSoap)(this)).GetAppStatus(inValue);
            return retVal.Body.GetAppStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JustExample.CallFSOP.GetAppStatusResponse> JustExample.CallFSOP.FSOPServerSoap.GetAppStatusAsync(JustExample.CallFSOP.GetAppStatusRequest request) {
            return base.Channel.GetAppStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<JustExample.CallFSOP.GetAppStatusResponse> GetAppStatusAsync(string strAppType, string strAppID, string strLicenseNo, string Token) {
            JustExample.CallFSOP.GetAppStatusRequest inValue = new JustExample.CallFSOP.GetAppStatusRequest();
            inValue.Body = new JustExample.CallFSOP.GetAppStatusRequestBody();
            inValue.Body.strAppType = strAppType;
            inValue.Body.strAppID = strAppID;
            inValue.Body.strLicenseNo = strLicenseNo;
            inValue.Body.Token = Token;
            return ((JustExample.CallFSOP.FSOPServerSoap)(this)).GetAppStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JustExample.CallFSOP.submitLegFlyFSOPXMLResponse JustExample.CallFSOP.FSOPServerSoap.submitLegFlyFSOPXML(JustExample.CallFSOP.submitLegFlyFSOPXMLRequest request) {
            return base.Channel.submitLegFlyFSOPXML(request);
        }
        
        public string submitLegFlyFSOPXML(string PfileName, string myfile, string Token) {
            JustExample.CallFSOP.submitLegFlyFSOPXMLRequest inValue = new JustExample.CallFSOP.submitLegFlyFSOPXMLRequest();
            inValue.Body = new JustExample.CallFSOP.submitLegFlyFSOPXMLRequestBody();
            inValue.Body.PfileName = PfileName;
            inValue.Body.myfile = myfile;
            inValue.Body.Token = Token;
            JustExample.CallFSOP.submitLegFlyFSOPXMLResponse retVal = ((JustExample.CallFSOP.FSOPServerSoap)(this)).submitLegFlyFSOPXML(inValue);
            return retVal.Body.submitLegFlyFSOPXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JustExample.CallFSOP.submitLegFlyFSOPXMLResponse> JustExample.CallFSOP.FSOPServerSoap.submitLegFlyFSOPXMLAsync(JustExample.CallFSOP.submitLegFlyFSOPXMLRequest request) {
            return base.Channel.submitLegFlyFSOPXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<JustExample.CallFSOP.submitLegFlyFSOPXMLResponse> submitLegFlyFSOPXMLAsync(string PfileName, string myfile, string Token) {
            JustExample.CallFSOP.submitLegFlyFSOPXMLRequest inValue = new JustExample.CallFSOP.submitLegFlyFSOPXMLRequest();
            inValue.Body = new JustExample.CallFSOP.submitLegFlyFSOPXMLRequestBody();
            inValue.Body.PfileName = PfileName;
            inValue.Body.myfile = myfile;
            inValue.Body.Token = Token;
            return ((JustExample.CallFSOP.FSOPServerSoap)(this)).submitLegFlyFSOPXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        JustExample.CallFSOP.UploadFileWithCallWcfResponse JustExample.CallFSOP.FSOPServerSoap.UploadFileWithCallWcf(JustExample.CallFSOP.UploadFileWithCallWcfRequest request) {
            return base.Channel.UploadFileWithCallWcf(request);
        }
        
        public void UploadFileWithCallWcf(byte[] fileStream, string callFunName, string fileName, string wcfCreateFileName, string tocken) {
            JustExample.CallFSOP.UploadFileWithCallWcfRequest inValue = new JustExample.CallFSOP.UploadFileWithCallWcfRequest();
            inValue.Body = new JustExample.CallFSOP.UploadFileWithCallWcfRequestBody();
            inValue.Body.fileStream = fileStream;
            inValue.Body.callFunName = callFunName;
            inValue.Body.fileName = fileName;
            inValue.Body.wcfCreateFileName = wcfCreateFileName;
            inValue.Body.tocken = tocken;
            JustExample.CallFSOP.UploadFileWithCallWcfResponse retVal = ((JustExample.CallFSOP.FSOPServerSoap)(this)).UploadFileWithCallWcf(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JustExample.CallFSOP.UploadFileWithCallWcfResponse> JustExample.CallFSOP.FSOPServerSoap.UploadFileWithCallWcfAsync(JustExample.CallFSOP.UploadFileWithCallWcfRequest request) {
            return base.Channel.UploadFileWithCallWcfAsync(request);
        }
        
        public System.Threading.Tasks.Task<JustExample.CallFSOP.UploadFileWithCallWcfResponse> UploadFileWithCallWcfAsync(byte[] fileStream, string callFunName, string fileName, string wcfCreateFileName, string tocken) {
            JustExample.CallFSOP.UploadFileWithCallWcfRequest inValue = new JustExample.CallFSOP.UploadFileWithCallWcfRequest();
            inValue.Body = new JustExample.CallFSOP.UploadFileWithCallWcfRequestBody();
            inValue.Body.fileStream = fileStream;
            inValue.Body.callFunName = callFunName;
            inValue.Body.fileName = fileName;
            inValue.Body.wcfCreateFileName = wcfCreateFileName;
            inValue.Body.tocken = tocken;
            return ((JustExample.CallFSOP.FSOPServerSoap)(this)).UploadFileWithCallWcfAsync(inValue);
        }
    }
}
